<p><label for="user_lastname">Lastname</label>
<?= text_field('user', 'lastname', $this->user); ?></p>
<p><label for="user_firstname">Firstname</label>
<?= text_field('user', 'firstname', $this->user); ?></p>
<p><label for="user_email">Email</label>
<?= text_field('user', 'email', $this->user); ?></p>
<p><label for="user_login">Login</label>
<?= text_field('user', 'login', $this->user); ?></p>
<p><label for="user_password">Password</label>
<?= text_field('user', 'password', $this->user); ?></p>
<p><label for="user_active">Active</label>
<?= check_box('user', 'active', $this->user); ?></p>
<p><label for="user_superuser">Superuser</label>
<?= check_box('user', 'superuser', $this->user); ?></p>
<p><label for="user_last_access">Last access</label>
<?= date_time_select('user', 'last_access', $this->user); ?></p>
<p><label for="user_created_on">Created on</label>
<?= date_time_select('user', 'created_on', $this->user); ?></p>
<p><label for="user_updated_on">Updated on</label>
<?= date_time_select('user', 'updated_on', $this->user); ?></p>
